accessibility:
  animations: true
appearance:
  dock: off
  dockScreen: current
  dockFill: 0.5
  dockSpace: 1
  dockHideOnBlur: false
  dockAlwaysOnTop: true
  flexTabs: false
  tabsLocation: left
  tabsInFullscreen: true
  cycleTabs: true
  theme: Standard (legacy)
  frame: thin
  css: '/* * { color: blue !important; } */'
  opacity: 1.0
  vibrancy: false
  vibrancyType: 'blur'
  lastTabClosesWindow: false
  spaciness: 1
  colorSchemeMode: 'dark'
terminal:
  showBuiltinProfiles: false
  showRecentProfiles: 3
  paneResizeStep: 0.1
  focusFollowsMouse: false
  identification: null
hotkeys:
  profile:
    __nonStructural: true
  profile-selectors:
    __nonStructural: true
profiles: []
groups: []
profileDefaults:
  __nonStructural: true
  ssh:
    disableDynamicTitle: true
recoverTabs: false
enableAnalytics: false
enableWelcomeTab: false
electronFlags:
  - ['force_discrete_gpu', '0']
enableAutomaticUpdates: false
version: 1
vault: null
encrypted: false
enableExperimentalFeatures: false
pluginBlacklist: []
commandBlacklist: []
providerBlacklist: []
profileBlacklist: []
hacks:
  disableGPU: false
  disableVibrancyWhileDragging: false
  enableFluentBackground: false
language: null
defaultQuickConnectProvider: "ssh"
